browser_profile_path: C:/Users/slaut/.ledger_fetch_chrome_profile
transactions_path: ./transactions
headless: false
timeout: 30000
rbc:
  enabled: true
wealthsimple:
  enabled: true

amex:
  enabled: true
  accounts:
    - id: "AMEX-91001" # The unique account ID found in accounts.csv
      invert_credit_transactions: true # Override the bank-level setting for this specific account

canadiantire:
  enabled: true
  days_to_fetch: 150
  accounts:
    - id: "CTFS-40024514" # The unique account ID found in accounts.csv

bmo:
  enabled: true
cibc:
  enabled: true
national_bank:
  enabled: true
